// <auto-generated />
using System;
using LibrarySystem.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystem.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("LibarySystem.Core.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-91-0-012345-6",
                            IsAvailable = true,
                            PublishedYear = 1954,
                            Title = "Sagan om ringen"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-91-0-012346-3",
                            IsAvailable = false,
                            PublishedYear = 1937,
                            Title = "Hobbiten"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.K. Rowling",
                            ISBN = "978-91-0-012347-0",
                            IsAvailable = true,
                            PublishedYear = 1997,
                            Title = "Harry Potter och de vises sten"
                        },
                        new
                        {
                            Id = 4,
                            Author = "George Orwell",
                            ISBN = "978-91-0-012348-7",
                            IsAvailable = true,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-0-012349-4",
                            IsAvailable = true,
                            PublishedYear = 1973,
                            Title = "Bröderna Lejonhjärta"
                        });
                });

            modelBuilder.Entity("LibarySystem.Core.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            DueDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1
                        });
                });

            modelBuilder.Entity("LibarySystem.Core.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.andersson@email.com",
                            MemberId = "M001",
                            MemberSince = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anna Andersson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bengt.svensson@email.com",
                            MemberId = "M002",
                            MemberSince = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bengt Svensson"
                        },
                        new
                        {
                            Id = 3,
                            Email = "cecilia.johansson@email.com",
                            MemberId = "M003",
                            MemberSince = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cecilia Johansson"
                        });
                });

            modelBuilder.Entity("LibarySystem.Core.Loan", b =>
                {
                    b.HasOne("LibarySystem.Core.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibarySystem.Core.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibarySystem.Core.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LibarySystem.Core.Member", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
